In [2]:
import h5py
import pandas as pd
import numpy as np

In [3]:
# gnm_cnts_path = "/mnt/beegfs/userdata/j_wang/Algorithm_Resources/dig/downloads/dig_data_files/genome_counts.h5"
gnm_cnts_path = "D:\data\genome_counts.h5"

In [4]:
with h5py.File(gnm_cnts_path, "r") as fd:
    for k in fd.keys():
        print(fd[k])

<HDF5 group "/all_window_genome_counts" (4 members)>
<HDF5 group "/genome_counts" (2 members)>
<HDF5 dataset "idx": shape (288091, 3), type "<i4">
<HDF5 dataset "mappability": shape (288091,), type "<f8">


In [4]:
fd = h5py.File(gnm_cnts_path, "r")

In [5]:
fd['all_window_genome_counts'].keys()

<KeysViewHDF5 ['axis0', 'axis1', 'block0_items', 'block0_values']>

In [17]:
fd['all_window_genome_counts']['axis0'][:]

array([b'AAA', b'AAC', b'AAG', b'AAT', b'ACA', b'ACC', b'ACG', b'ACT',
       b'AGA', b'AGC', b'AGG', b'AGT', b'ATA', b'ATC', b'ATG', b'ATT',
       b'CAA', b'CAC', b'CAG', b'CAT', b'CCA', b'CCC', b'CCG', b'CCT',
       b'CGA', b'CGC', b'CGG', b'CGT', b'CTA', b'CTC', b'CTG', b'CTT',
       b'GAA', b'GAC', b'GAG', b'GAT', b'GCA', b'GCC', b'GCG', b'GCT',
       b'GGA', b'GGC', b'GGG', b'GGT', b'GTA', b'GTC', b'GTG', b'GTT',
       b'TAA', b'TAC', b'TAG', b'TAT', b'TCA', b'TCC', b'TCG', b'TCT',
       b'TGA', b'TGC', b'TGG', b'TGT', b'TTA', b'TTC', b'TTG', b'TTT'],
      dtype='|S3')

In [18]:
fd['all_window_genome_counts']['axis1'][:]

array([b'chr1:0-10000', b'chr1:10000-20000', b'chr1:20000-30000', ...,
       b'chr22:51270000-51280000', b'chr22:51280000-51290000',
       b'chr22:51290000-51300000'], dtype='|S25')

In [19]:
fd['all_window_genome_counts']['block0_items'][:]

array([b'AAA', b'AAC', b'AAG', b'AAT', b'ACA', b'ACC', b'ACG', b'ACT',
       b'AGA', b'AGC', b'AGG', b'AGT', b'ATA', b'ATC', b'ATG', b'ATT',
       b'CAA', b'CAC', b'CAG', b'CAT', b'CCA', b'CCC', b'CCG', b'CCT',
       b'CGA', b'CGC', b'CGG', b'CGT', b'CTA', b'CTC', b'CTG', b'CTT',
       b'GAA', b'GAC', b'GAG', b'GAT', b'GCA', b'GCC', b'GCG', b'GCT',
       b'GGA', b'GGC', b'GGG', b'GGT', b'GTA', b'GTC', b'GTG', b'GTT',
       b'TAA', b'TAC', b'TAG', b'TAT', b'TCA', b'TCC', b'TCG', b'TCT',
       b'TGA', b'TGC', b'TGG', b'TGT', b'TTA', b'TTC', b'TTG', b'TTT'],
      dtype='|S3')

In [22]:
fd['all_window_genome_counts']['block0_values']

<HDF5 dataset "block0_values": shape (288091, 64), type "<i8">

In [23]:
fd['all_window_genome_counts']['block0_values'][:]

array([[  0,   0,   0, ...,   0,   0,   0],
       [104, 150, 152, ..., 117, 124,  95],
       [235, 127, 186, ..., 165, 120, 202],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [7]:
fd['genome_counts'].keys()

<KeysViewHDF5 ['index', 'values']>

In [13]:
fd['genome_counts']['values'][:]

array([102756867,  38968630,  53472745,  66644197,  53929168,  31245084,
         6784231,  43147628,  59278134,  37688084,  47839059,  43193345,
        54984912,  35743922,  49137747,  66731099,  50588852,  40407193,
        54611018,  49148814,  49558494,  35511012,   7514715,  47895757,
         5956046,   6481476,   7513417,   6801733,  34503547,  45389734,
        54653897,  53563412,  52790167,  25378340,  45373956,  35774914,
        38730044,  32205620,   6486059,  37696534,  41535378,  32186850,
        35532041,  31271068,  30362695,  25416575,  40493555,  39104026,
        55706539,  30351944,  34540906,  55029755,  52538174,  41518263,
         5967666,  59370668,  52547664,  38761846,  49640832,  54110707,
        55777982,  52844680,  50775852, 103101929], dtype=int64)

In [14]:
fd['genome_counts']['index'][:]

array([b'AAA', b'AAC', b'AAG', b'AAT', b'ACA', b'ACC', b'ACG', b'ACT',
       b'AGA', b'AGC', b'AGG', b'AGT', b'ATA', b'ATC', b'ATG', b'ATT',
       b'CAA', b'CAC', b'CAG', b'CAT', b'CCA', b'CCC', b'CCG', b'CCT',
       b'CGA', b'CGC', b'CGG', b'CGT', b'CTA', b'CTC', b'CTG', b'CTT',
       b'GAA', b'GAC', b'GAG', b'GAT', b'GCA', b'GCC', b'GCG', b'GCT',
       b'GGA', b'GGC', b'GGG', b'GGT', b'GTA', b'GTC', b'GTG', b'GTT',
       b'TAA', b'TAC', b'TAG', b'TAT', b'TCA', b'TCC', b'TCG', b'TCT',
       b'TGA', b'TGC', b'TGG', b'TGT', b'TTA', b'TTC', b'TTG', b'TTT'],
      dtype='|S3')

In [8]:
fd['idx'][0]

array([    1,     0, 10000])

In [4]:
fd['mappability']

<HDF5 dataset "mappability": shape (288091,), type "<f8">

In [9]:
np.array(fd['mappability'][:])

array([0.        , 0.13808968, 0.16584463, ..., 0.        , 0.        ,
       0.        ])

In [11]:
fd['all_window_genome_counts']['axis0']

<HDF5 dataset "axis0": shape (64,), type "|S3">

In [12]:
fd['all_window_genome_counts']['axis1']

<HDF5 dataset "axis1": shape (288091,), type "|S25">

In [13]:
fd['all_window_genome_counts']['block0_items']

<HDF5 dataset "block0_items": shape (64,), type "|S3">

In [14]:
fd['all_window_genome_counts']['block0_values']

<HDF5 dataset "block0_values": shape (288091, 64), type "<i8">

In [15]:
fd['genome_counts']['index']

<HDF5 dataset "index": shape (64,), type "|S3">

In [16]:
fd['genome_counts']['values']

<HDF5 dataset "values": shape (64,), type "<i8">

In [17]:
fd['genome_counts']['index'][:]

array([b'AAA', b'AAC', b'AAG', b'AAT', b'ACA', b'ACC', b'ACG', b'ACT',
       b'AGA', b'AGC', b'AGG', b'AGT', b'ATA', b'ATC', b'ATG', b'ATT',
       b'CAA', b'CAC', b'CAG', b'CAT', b'CCA', b'CCC', b'CCG', b'CCT',
       b'CGA', b'CGC', b'CGG', b'CGT', b'CTA', b'CTC', b'CTG', b'CTT',
       b'GAA', b'GAC', b'GAG', b'GAT', b'GCA', b'GCC', b'GCG', b'GCT',
       b'GGA', b'GGC', b'GGG', b'GGT', b'GTA', b'GTC', b'GTG', b'GTT',
       b'TAA', b'TAC', b'TAG', b'TAT', b'TCA', b'TCC', b'TCG', b'TCT',
       b'TGA', b'TGC', b'TGG', b'TGT', b'TTA', b'TTC', b'TTG', b'TTT'],
      dtype='|S3')

In [18]:
fd['genome_counts']['values'][:]

array([102756867,  38968630,  53472745,  66644197,  53929168,  31245084,
         6784231,  43147628,  59278134,  37688084,  47839059,  43193345,
        54984912,  35743922,  49137747,  66731099,  50588852,  40407193,
        54611018,  49148814,  49558494,  35511012,   7514715,  47895757,
         5956046,   6481476,   7513417,   6801733,  34503547,  45389734,
        54653897,  53563412,  52790167,  25378340,  45373956,  35774914,
        38730044,  32205620,   6486059,  37696534,  41535378,  32186850,
        35532041,  31271068,  30362695,  25416575,  40493555,  39104026,
        55706539,  30351944,  34540906,  55029755,  52538174,  41518263,
         5967666,  59370668,  52547664,  38761846,  49640832,  54110707,
        55777982,  52844680,  50775852, 103101929], dtype=int64)

In [19]:
fd.attrs.keys()

<KeysViewHDF5 ['collapse', 'n_down', 'n_up']>

In [20]:
fd['all_window_genome_counts'].attrs.keys()

<KeysViewHDF5 ['CLASS', 'TITLE', 'VERSION', 'axis0_variety', 'axis1_variety', 'block0_items_variety', 'encoding', 'errors', 'nblocks', 'ndim', 'pandas_type', 'pandas_version']>

In [21]:
fd['genome_counts'].attrs.keys()

<KeysViewHDF5 ['CLASS', 'TITLE', 'VERSION', 'encoding', 'errors', 'index_variety', 'name', 'pandas_type', 'pandas_version']>

In [22]:
fd['idx'][:]

array([[       1,        0,    10000],
       [       1,    10000,    20000],
       [       1,    20000,    30000],
       ...,
       [      22, 51270000, 51280000],
       [      22, 51280000, 51290000],
       [      22, 51290000, 51300000]])

In [26]:
from scipy import stats
import random

In [39]:
rl = np.random.randint(10, size=20)
rl

array([1, 5, 9, 8, 0, 2, 0, 6, 4, 5, 1, 6, 3, 1, 6, 3, 7, 6, 1, 9])

In [43]:
stats.mstats.rankdata(rl)

array([ 4.5, 11.5, 19.5, 18. ,  1.5,  7. ,  1.5, 14.5, 10. , 11.5,  4.5,
       14.5,  8.5,  4.5, 14.5,  8.5, 17. , 14.5,  4.5, 19.5])

In [42]:
stats.mstats.rankdata(rl)/len(rl)

array([0.225, 0.575, 0.975, 0.9  , 0.075, 0.35 , 0.075, 0.725, 0.5  ,
       0.575, 0.225, 0.725, 0.425, 0.225, 0.725, 0.425, 0.85 , 0.725,
       0.225, 0.975])

In [45]:
import tensorboardX